src/Ens/TostainGuillaumeBundle/Entity/Job.php
<?php

namespace Ens\TostainGuillaumeBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Ens\TostainGuillaumeBundle\Utils\Jobeet as Jobeet;

/**
 * Job
 */
class Job
{
    /**
     * @var integer
     */
    private $id;

    /**
     * @var string
     */
    private $type;

    /**
     * @var string
     */
    private $company;

    /**
     * @var string
     */
    private $logo;

    /**
     * @var string
     */
    private $url;

    /**
     * @var string
     */
    private $position;

    /**
     * @var string
     */
    private $location;

    /**
     * @var string
     */
    private $description;

    /**
     * @var string
     */
    private $how_to_apply;

    /**
     * @var string
     */
    private $token;

    /**
     * @var boolean
     */
    private $is_public;

    /**
     * @var boolean
     */
    private $is_activated;

    /**
     * @var string
     */
    private $email;

    /**
     * @var \DateTime
     */
    private $expires_at;

    /**
     * @var \DateTime
     */
    private $created_at;

    /**
     * @var \DateTime
     */
    private $updated_at;

    /**
     * @var \Ens\TostainGuillaumeBundle\Entity\Category
     */
    private $category;

    public $file;

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set type
     *
     * @param string $type
     * @return Job
     */
    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Get type
     *
     * @return string 
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Set company
     *
     * @param string $company
     * @return Job
     */
    public function setCompany($company)
    {
        $this->company = $company;

        return $this;
    }

    /**
     * Get company
     *
     * @return string 
     */
    public function getCompany()
    {
        return $this->company;
    }

    /**
     * Set logo
     *
     * @param string $logo
     * @return Job
     */
    public function setLogo($logo)
    {
        $this->logo = $logo;

        return $this;
    }

    /**
     * Get logo
     *
     * @return string 
     */
    public function getLogo()
    {
        return $this->logo;
    }

    /**
     * Set url
     *
     * @param string $url
     * @return Job
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get url
     *
     * @return string 
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Set position
     *
     * @param string $position
     * @return Job
     */
    public function setPosition($position)
    {
        $this->position = $position;

        return $this;
    }

    /**
     * Get position
     *
     * @return string 
     */
    public function getPosition()
    {
        return $this->position;
    }

    /**
     * Set location
     *
     * @param string $location
     * @return Job
     */
    public function setLocation($location)
    {
        $this->location = $location;

        return $this;
    }

    /**
     * Get location
     *
     * @return string 
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return Job
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string 
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set how_to_apply
     *
     * @param string $howToApply
     * @return Job
     */
    public function setHowToApply($howToApply)
    {
        $this->how_to_apply = $howToApply;

        return $this;
    }

    /**
     * Get how_to_apply
     *
     * @return string 
     */
    public function getHowToApply()
    {
        return $this->how_to_apply;
    }

    /**
     * Set token
     *
     * @param string $token
     * @return Job
     */
    public function setToken($token)
    {
        $this->token = $token;

        return $this;
    }

    /**
     * Get token
     *
     * @return string 
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * Set is_public
     *
     * @param boolean $isPublic
     * @return Job
     */
    public function setIsPublic($isPublic)
    {
        $this->is_public = $isPublic;

        return $this;
    }

    /**
     * Get is_public
     *
     * @return boolean 
     */
    public function getIsPublic()
    {
        return $this->is_public;
    }

    /**
     * Set is_activated
     *
     * @param boolean $isActivated
     * @return Job
     */
    public function setIsActivated($isActivated)
    {
        $this->is_activated = $isActivated;

        return $this;
    }

    /**
     * Get is_activated
     *
     * @return boolean 
     */
    public function getIsActivated()
    {
        return $this->is_activated;
    }

    /**
     * Set email
     *
     * @param string $email
     * @return Job
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string 
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set expires_at
     *
     * @param \DateTime $expiresAt
     * @return Job
     */
    public function setExpiresAt($expiresAt)
    {
        $this->expires_at = $expiresAt;

        return $this;
    }

    /**
     * Get expires_at
     *
     * @return \DateTime 
     */
    public function getExpiresAt()
    {
        return $this->expires_at;
    }

    /**
     * Set created_at
     *
     * @param \DateTime $createdAt
     * @return Job
     */
    public function setCreatedAt($createdAt)
    {
        $this->created_at = $createdAt;

        return $this;
    }

    /**
     * Get created_at
     *
     * @return \DateTime 
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Set updated_at
     *
     * @param \DateTime $updatedAt
     * @return Job
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updated_at = $updatedAt;

        return $this;
    }

    /**
     * Get updated_at
     *
     * @return \DateTime 
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Set category
     *
     * @param \Ens\TostainGuillaumeBundle\Entity\Category $category
     * @return Job
     */
    public function setCategory(\Ens\TostainGuillaumeBundle\Entity\Category $category = null)
    {
        $this->category = $category;

        return $this;
    }

    /**
     * Get category
     *
     * @return \Ens\TostainGuillaumeBundle\Entity\Category 
     */
    public function getCategory()
    {
        return $this->category;
    }
    /**
     * @ORM\PrePersist
     */
    public function setCreatedAtValue()
    {
        $this->created_at = new \DateTime();
    }

    /**
     * @ORM\PreUpdate
     */
    public function setUpdatedAtValue()
    {
        $this->updated_at = new \DateTime();
    }

    public function getCompanySlug()
    {
        return Jobeet::slugify($this->getCompany());
    }

    public function getPositionSlug()
    {
        return Jobeet::slugify($this->getPosition());
    }

    public function getLocationSlug()
    {
        return Jobeet::slugify($this->getLocation());
    }

    /**
     * @ORM\PrePersist
     */
    public function setExpiresAtValue()
    {
        if(!$this->getExpiresAt())
        {
            $now = $this->getCreatedAt() ? $this->getCreatedAt()->format('U') : time();
            $this->expires_at = new \DateTime(date('Y-m-d H:i:s', $now + 86400 * 30));
        }
    }

    public static function getTypes()
    {
        return array('full-time' => 'Full time', 'part-time' => 'Part time', 'freelance' => 'Freelance');
    }

    public static function getTypeValues()
    {
        return array_keys(self::getTypes());
    }

    protected function getUploadDir()
    {
        return 'uploads/jobs';
    }

    protected function getUploadRootDir()
    {
        return __DIR__.'/../../../../web/'.$this->getUploadDir();
    }

    public function getWebPath()
    {
        return null === $this->logo ? null : $this->getUploadDir().'/'.$this->logo;
    }

    public function getAbsolutePath()
    {
        return null === $this->logo ? null : $this->getUploadRootDir().'/'.$this->logo;
    }

    /**
     * @ORM\PrePersist
     */
    public function preUpload()
    {
        if (null !== $this->file) {
            // do whatever you want to generate a unique name
            $this->logo = uniqid().'.'.$this->file->guessExtension();
        }
    }

    /**
     * @ORM\PostPersist
     */
    public function upload()
    {
        if (null === $this->file) {
            return;
        }

        // if there is an error when moving the file, an exception will
        // be automatically thrown by move(). This will properly prevent
        // the entity from being persisted to the database on error
        $this->file->move($this->getUploadRootDir(), $this->logo);

        unset($this->file);
    }

    /**
     * @ORM\PostRemove
     */
    public function removeUpload()
    {
        if ($file = $this->getAbsolutePath()) {
            unlink($file);
        }
    }

    public function setTokenValue()
    {
        if(!$this->getToken())
        {
            $this->token = sha1($this->getEmail().rand(11111, 99999));
        }
    }

    public function isExpired()
    {
        return $this->getDaysBeforeExpires() < 0;
    }

    public function expiresSoon()
    {

src/Ens/TostainGuillaumeBundle/Form/JobType.php
<?php

namespace Ens\TostainGuillaumeBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Ens\TostainGuillaumeBundle\Entity\Job;

class JobType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('category')
            ->add('company')
            ->add('url')
            ->add('position')
            ->add('location')
            ->add('description')
            ->add('email')
            ->add('type', 'choice', array('choices' => Job::getTypes(), 'expanded' => true))
            ->add('how_to_apply', null, array('label' => 'How to apply?'))
            ->add('is_public', null, array('label' => 'Public?'))
            ->add('file', 'file', array('label' => 'Company logo', 'required' => false))
        ;
    }

    public function getName()
    {
        return 'job';
    }
    
    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Ens\TostainGuillaumeBundle\Entity\Job'
        ));
    }
}

src/Ens/TostainGuillaumeBundle/Resources/views/job/admin.html.twig
<div id="job_actions">
    <h3>Admin</h3>
    <ul>
        {% if not job.isActivated %}
            <li><a href="{{ path('job_edit', { 'token': job.token }) }}">Edit</a></li>
            <li>
                <form action="{{ path('job_publish', { 'token': job.token }) }}" method="post">
                    {{ form_widget(publish_form) }}
                    <button type="submit">Publish</button>
                </form>
            </li>
        {% endif %}
        <li>
            <form action="{{ path('job_delete', { 'token': job.token }) }}" method="post">
                {{ form_widget(delete_form) }}
                <button type="submit" onclick="if(!confirm('Are you sure?')) { return false; }">Delete</button>
            </form>
        </li>
        {% if job.isActivated %}
            <li {% if job.expiresSoon %} class="expires_soon" {% endif %}>
                {% if job.isExpired %}
                    Expired
                {% else %}
                    Expires in <strong>{{ job.getDaysBeforeExpires }}</strong> days
                {% endif %}

                {% if job.expiresSoon %}
                    <form action="{{ path('job_extend', { 'token': job.token }) }}" method="post">
                        {{ form_widget(extend_form) }}
                        <button type="submit">Extend</button> for another 30 days
                    </form>
                {% endif %}
            </li>
        {% else %}
            <li>
                [Bookmark this <a href="{{ url('job_preview', { 'token': job.token, 'company': job.companySlug, 'location': job.locationSlug, 'position': job.positionSlug }) }}">URL</a> to manage this job in the future.]
            </li>
        {% endif %}
    </ul>
</div>

src/Ens/TostainGuillaumeBundle/Resources/views/job/edit.html.twig
{% extends 'EnsTostainGuillaumeBundle::layout.html.twig' %}

{% form_theme form 'bootstrap_3_layout.html.twig' %}

{% block field_errors %}
    {% spaceless %}
        {% if errors|length > 0 %}
            <ul>
                {% for error in errors %}
                    <li>{{ error.messageTemplate|trans(error.messageParameters, 'validators') }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endspaceless %}
{% endblock field_errors %}

{% block content %}
    <h1>Job edit</h1>
    <form action="{{ path('job_update', { 'token': job.token }) }}" method="post" {{ form_enctype(edit_form) }}>
        <table id="job_form">
            <tfoot>
            <tr>
                <td colspan="2">
                    <input type="submit" value="Preview your job" />
                </td>
            </tr>
            </tfoot>
            <tbody>
            <tr>
                <th>{{ form_label(edit_form.category) }}</th>
                <td>
                    {{ form_errors(edit_form.category) }}
                    {{ form_widget(edit_form.category) }}
                </td>
            </tr>
            <tr>
                <th>{{ form_label(edit_form.type) }}</th>
                <td>
                    {{ form_errors(edit_form.type) }}
                    {{ form_widget(edit_form.type) }}
                </td>
            </tr>
            <tr>
                <th>{{ form_label(edit_form.company) }}</th>
                <td>
                    {{ form_errors(edit_form.company) }}
                    {{ form_widget(edit_form.company) }}
                </td>
            </tr>
            <tr>
                <th>{{ form_label(edit_form.file) }}</th>
                <td>
                    {{ form_errors(edit_form.file) }}
                    {{ form_widget(edit_form.file) }}
                </td>
            </tr>
            <tr>
                <th>{{ form_label(edit_form.url) }}</th>
                <td>
                    {{ form_errors(edit_form.url) }}
                    {{ form_widget(edit_form.url) }}
                </td>
            </tr>
            <tr>
                <th>{{ form_label(edit_form.position) }}</th>
                <td>
                    {{ form_errors(edit_form.position) }}
                    {{ form_widget(edit_form.position) }}
                </td>
            </tr>
            <tr>
                <th>{{ form_label(edit_form.location) }}</th>
                <td>
                    {{ form_errors(edit_form.location) }}
                    {{ form_widget(edit_form.location) }}
                </td>
            </tr>
            <tr>
                <th>{{ form_label(edit_form.description) }}</th>
                <td>
                    {{ form_errors(edit_form.description) }}
                    {{ form_widget(edit_form.description) }}
                </td>
            </tr>
            <tr>
                <th>{{ form_label(edit_form.how_to_apply) }}</th>
                <td>
                    {{ form_errors(edit_form.how_to_apply) }}
                    {{ form_widget(edit_form.how_to_apply) }}
                </td>
            </tr>
            <tr>
                <th>{{ form_label(edit_form.is_public) }}</th>
                <td>
                    {{ form_errors(edit_form.is_public) }}
                    {{ form_widget(edit_form.is_public) }}
                    <br /> Whether the job can also be published on affiliate websites or not.
                </td>
            </tr>
            <tr>
                <th>{{ form_label(edit_form.email) }}</th>
                <td>
                    {{ form_errors(edit_form.email) }}
                    {{ form_widget(edit_form.email) }}
                </td>
            </tr>
            </tbody>
        </table>

        {{ form_rest(edit_form) }}
    </form>
{% endblock %}

src/Ens/TostainGuillaumeBundle/Resources/views/job/index.atom.twig
<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
    <title>Jobeet</title>
    <subtitle>Latest Jobs</subtitle>
    <link href="{{ url('job_index', {'_format': 'atom'}) }}" rel="self"/>
    <link href="{{ url('ens_tostain_guillaume_homepage') }}"/>
    <updated>{{ lastUpdated }}</updated>
    <author><name>Jobeet</name></author>
    <id>{{ feedId }}</id>


    {% for category in categories %}
        {% for job in category.activejobs %}
            <entry>
                <title>{{ job.position }} ({{ job.location }})</title>
                <link href="{{ url('job_show', { 'id': job.id, 'company': job.companyslug, 'location': job.locationslug, 'position': job.positionslug }) }}" />
                <id>{{ job.id }}</id>
                <updated>{{ job.createdAt.format(constant('DATE_ATOM')) }}</updated>
                <summary type="xhtml">
                    <div xmlns="http://www.w3.org/1999/xhtml">
                        {% if job.logo %}
                            <div>
                                <a href="{{ job.url }}">
                                    <img src="http://{{ app.request.host }}/uploads/jobs/{{ job.logo }}" alt="{{ job.company }} logo" />
                                </a>
                            </div>
                        {% endif %}
                        <div>
                            {{ job.description|nl2br }}
                        </div>
                        <h4>How to apply?</h4>
                        <p>{{ job.howtoapply }}</p>
                    </div>
                </summary>
                <author><name>{{ job.company }}</name></author>
            </entry>
        {% endfor %}
    {% endfor %}

</feed>

src/Ens/TostainGuillaumeBundle/Resources/views/job/index.html.twig
{% extends 'EnsTostainGuillaumeBundle::layout.html.twig' %}
{% block stylesheets %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
{% endblock %}
{% block javascripts %}
        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
{% endblock %}
{% block content %}
    <div id="jobs">
        {% for category in categories %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h1 class="panel-title">
                        <a href="{{ path('ens_tostain_guillaume_category', { 'slug': category.slug }) }}">{{ category.name }}</a>
                        <small>
                            <a href="""{{ path('job_index', {'_format': 'atom'}) }}">
                            <span>Feed</span>
                            <i class="fa fa-rss" aria-hidden="true"></i>
                            </a>
                        </small>
                    </h1>
                </div>
                <div class="panel-body">
                    {% include '@EnsTostainGuillaume/job/list.html.twig' with {'jobs': category.activejobs} %}
                    {% if category.morejobs %}
                    and <a href="{{ path('ens_tostain_guillaume_category', { 'slug': category.slug }) }}">{{ category.morejobs }}</a>
                    more...
                {% endif %}
                </div>
            </div>

        {% endfor %}
    </div>
{% endblock %}

src/Ens/TostainGuillaumeBundle/Resources/views/job/list.html.twig
<table class="table table-striped">
    {% for job in jobs %}
        <tr class="{{ cycle(['even', 'odd'], loop.index) }}">
            <td class="location">{{ job.location }}</td>
            <td class="position">
                <a href="{{ path('job_show', { 'id': job.id, 'company': job.companySlug, 'location': job.locationSlug, 'position': job.positionSlug }) }}">
                    {{ job.position }}
                </a>
            </td>
            <td class="company">{{ job.company }}</td>
        </tr>
    {% endfor %}
</table>

src/Ens/TostainGuillaumeBundle/Resources/views/job/new.html.twig
{% extends 'EnsTostainGuillaumeBundle::layout.html.twig' %}

{% form_theme form 'bootstrap_3_layout.html.twig' %}

{% block field_errors %}
    {% spaceless %}
        {% if errors|length > 0 %}
            <ul class="error_list">
                {% for error in errors %}
                    <li>{{ error.messageTemplate|trans(error.messageParameters, 'validators') }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endspaceless %}
{% endblock field_errors %}

{% block stylesheets %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
{% endblock %}
{% block javascripts %}
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
{% endblock %}

{% block content %}
    <h1>Job creation</h1>
    <form action="{{ path('job_new') }}" method="post" {{ form_enctype(form) }}>
        <table id="job_form">
            <tfoot>
            <tr>
                <td colspan="2">
                    <input type="submit" value="Preview your job" />
                </td>
            </tr>
            </tfoot>
            <tbody>
            <tr>
                <th>{{ form_label(form.category) }}</th>
                <td>
                    {{ form_errors(form.category) }}
                    {{ form_widget(form.category) }}
                </td>
            </tr>
            <tr>
                <th>{{ form_label(form.type) }}</th>
                <td>
                    {{ form_errors(form.type) }}
                    {{ form_widget(form.type) }}
                </td>
            </tr>
            <tr>
                <th>{{ form_label(form.company) }}</th>
                <td>
                    {{ form_errors(form.company) }}
                    {{ form_widget(form.company) }}
                </td>
            </tr>
            <tr>
                <th>{{ form_label(form.file) }}</th>
                <td>
                    {{ form_errors(form.file) }}
                    {{ form_widget(form.file) }}
                </td>
            </tr>
            <tr>
                <th>{{ form_label(form.url) }}</th>
                <td>
                    {{ form_errors(form.url) }}
                    {{ form_widget(form.url) }}
                </td>
            </tr>
            <tr>
                <th>{{ form_label(form.position) }}</th>
                <td>
                    {{ form_errors(form.position) }}
                    {{ form_widget(form.position) }}
                </td>
            </tr>
            <tr>
                <th>{{ form_label(form.location) }}</th>
                <td>
                    {{ form_errors(form.location) }}
                    {{ form_widget(form.location) }}
                </td>
            </tr>
            <tr>
                <th>{{ form_label(form.description) }}</th>
                <td>
                    {{ form_errors(form.description) }}
                    {{ form_widget(form.description) }}
                </td>
            </tr>
            <tr>
                <th>{{ form_label(form.how_to_apply) }}</th>
                <td>
                    {{ form_errors(form.how_to_apply) }}
                    {{ form_widget(form.how_to_apply) }}
                </td>
            </tr>
            <tr>
                <th>{{ form_label(form.is_public) }}</th>
                <td>
                    {{ form_errors(form.is_public) }}
                    {{ form_widget(form.is_public) }}
                    <br /> Whether the job can also be published on affiliate websites or not.
                </td>
            </tr>
            <tr>
                <th>{{ form_label(form.email) }}</th>
                <td>
                    {{ form_errors(form.email) }}
                    {{ form_widget(form.email) }}
                </td>
            </tr>
            </tbody>
        </table>

        {{ form_rest(form) }}
    </form>
{% endblock %}

src/Ens/TostainGuillaumeBundle/Resources/views/job/show.html.twig
{% extends 'EnsTostainGuillaumeBundle::layout.html.twig' %}
{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('bundles/enstostainguillaume/css/job.css') }}" type="text/css" media="all" />
{% endblock %}
{% block content %}
    {% if app.request.get('token') %}
        {% include 'EnsTostainGuillaumeBundle:Job:admin.html.twig' with {'job': job} %}
    {% endif %}
    <div id="job">
        <h1>{{ job.company }}</h1>
        <h2>{{ job.location }}</h2>
        <h3>
            {{ job.position }}
            <small> - {{ job.type }}</small>
        </h3>

        {% if job.logo %}
            <div class="logo">
                <a href="{{ job.url }}">
                    <img src="/uploads/jobs/{{ job.logo }}"
                         alt="{{ job.company }} logo" />
                </a>
            </div>
        {% endif %}

        <div class="description">
            {{ job.description|nl2br }}
        </div>

        <h4>How to apply?</h4>

        <p class="how_to_apply">{{ job.howtoapply }}</p>

        <div class="meta">
            <small>posted on {{ job.createdat|date('m/d/Y') }}</small>
        </div>

        <div style="padding: 20px 0">
            <a href="{{ path('job_edit', { 'token': job.token }) }}">

                Edit
            </a>
        </div>
    </div>
{% endblock %}